# -*- coding: utf-8 -*-
"""sale_price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/michael-borck/isys2001-worksheets/blob/main/sale_price.ipynb

# Sales Price

A local department store needs to develop a program that will computer the total price (including goods and services tax) of the item on sale when given an item's original price and discount percentage.

## Tasks
* Save to Github
* Design Algorithm
* Write and test the program in Python
"""

def calculate_total_price(original_price, discount_percentage):
    # Calculate the discounted price
    discounted_price = original_price - (original_price * (discount_percentage / 100))

    # Calculate GST (assuming GST is 10%)
    gst = discounted_price * 0.1

    # Calculate total price including GST
    total_price = discounted_price + gst

    return total_price

def main():
    # Input original price and discount percentage
    original_price = float(input("Enter the original price of the item: "))
    discount_percentage = float(input("Enter the discount percentage: "))

    # Calculate total price
    total_price = calculate_total_price(original_price, discount_percentage)

    # Display the total price
    print("Total price (including GST): ${:.2f}".format(total_price))

if __name__ == "__main__":
    main()

help(calculate_total_price)